# ==========================================================
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL (SUPABASE)
# ==========================================================

db.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
db.user=postgres.cgexvsytoxdzronnmjlm
db.password=H910j-@PEEEE
